# Generated by Django 4.2.2 on 2023-08-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('mobile', models.IntegerField()),
                ('timedate', models.DateTimeField()),
                ('details', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250, unique=True)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
