# Generated by Django 4.2.2 on 2023-08-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=250),
        ),
    ]
