# Generated by Django 4.2 on 2023-08-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskbook', '0002_alter_userinfo_email_alter_userinfo_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterModelTable(
            name='taskinfo',
            table='taskinfo',
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='userinfo',
        ),
    ]
