# Generated by Django 4.2 on 2023-08-11 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskbook', '0004_taskinfo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskinfo',
            old_name='user',
            new_name='usertask',
        ),
    ]
