# Generated by Django 4.2 on 2023-08-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskbook', '0005_rename_user_taskinfo_usertask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='usertask',
            field=models.CharField(max_length=150),
        ),
    ]
