# Generated by Django 4.2 on 2023-08-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskbook', '0007_userinfo_groups_userinfo_is_active_userinfo_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
