# Generated by Django 4.2 on 2023-08-24 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskbook', '0008_remove_userinfo_groups_remove_userinfo_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
