# Generated by Django 4.2 on 2023-08-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskbook', '0009_taskinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='timedate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
