# Generated by Django 4.2 on 2023-08-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskbook', '0010_alter_taskinfo_timedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='timedate',
            field=models.DateTimeField(),
        ),
    ]
